monitor.alsa.rules = [
  {
    matches = [{ node.name = "alsa_output.usb-FIIO_FIIO_KA11-01.analog-stereo" }]
    actions = {
      update-props = {
        priority.session = 2000
        audio.rate       = 96000
        audio.format     = "S32LE"
        audio.channels   = 2
      }
    }
  }
  {
    matches = [{ node.name = "rnnoise_source" }]
    actions = {
      update-props = {
        priority.session = 2000
      }
    }
  }
]
